#!/bin/bash
NEW_PASSWORD=$1

set -e

echo ${NEW_PASSWORD},admin,admin,\"system:masters\" | sudo tee /var/snap/microk8s/current/credentials/basic_auth.csv
sudo sed -i -e "s/password: \(.*\)/password: ${NEW_PASSWORD}/g" /var/snap/microk8s/current/credentials/client.config
sudo microk8s.stop
sudo microk8s.start
/snap/bin/microk8s.config -l > ~/.kube/config
